.TH DDS 8 "15 Jun 2006"

.SH NAME
dds \- DoS/DDoS Detecting System

.SH SYNOPSIS
.B dds
[\-d] [\-p] [\-r] [\-v <level>] [\-F] [\-h] [\-i \fI<iface>\fP] [\-b \fI<ip>:<port>\fP|-s] [\fI<config>\fP]

.SH DESCRIPTION
.PP
The \fIdds\fP is a DoS/DDoS detecting system.
It listen the uplink interface on a PC router or monitoring (SNAP)
port and collect traffic statistics. If traffic to a selected network
or to a single host in selected network more then normal (according
to specified in the config file rules), dds reports about this
incident via email or by any other method.
Another possibility is to detect DoS and DDoS attacks based on
netflow export information from a router. The \fIdds\fP currently
supports netflow versions 1 and 5.

.SH OPTIONS
.l The \fIdds\fP accepts the following options:
.TP 10
.B -h
Display a list of all commandline options.
.TP 10
.B -i \fI<iface>\fP
Listen specified interface (override config settings).
.TP 10
.B -b \fI<ip>:<port>\fP
Receive netflow to specified ip and port (override config settings).
.TP 10
.B -d
Daemonize.
.TP 10
.B -p
Don't put the interface into promiscuous mode.
.TP 10
.B -s
Read flow-tools storage data from stdin, not from network.
.TP 10
.B -v \fI<level>\fP
Set verbose level.
.TP 10
.B -F
Process packets for already filtered out attacks (netflow).
.TP 10
.B -r
Reversing in/out checks. Use this switch if you want to inspect
channel to your downlink. Traffic from you to the downlink in
this case will be checked as incoming traffic.

.SH SIGNALS
.TP 10
.BI SIGHUP
Causes \fIdds\fP to reread config-file.
.TP 10
.BI SIGUSR1
Causes \fIdds\fP to write info about all received traffic to snap-file
during 60 sec.
.TP 10
.BI SIGUSR2
Causes \fIdds\fP to restart itself.

.SH AUTHORS
Pavel Gulchouck <gul@gul.kiev.ua>.

